version: "2"
name: "telegram-time-tracker-bot"
description: "Бот для отслеживания рабочего времени и заработка"

services:
  bot:
    image: telegram-time-tracker-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_PATH=/app/data/time_tracker.db
    volumes:
      - base:/app/data

volumes:
  base:
    external: true 