version: '3'
name: "telegram-time-tracker-bot"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-time-tracker-bot
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_PATH=/app/data/time_tracker.db
    command: python main.py 